[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.8"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cap_guard = "C8RGfQJMVyUEGS9bMKoMnfvU1mZJYQ35dVdhxQSZ5iqr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
